name: Main Workflow
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node@22
        uses: actions/setup-node@v4
        with:
          node-version: '22'

      - name: Install dependencies
        run: | 
          npm ci --verbose

      - name: Run unit tests 
        run: |
          npx jest .
